### ISSUE TITLE
Path mapping doesn't always work as intended

### ISSUE THREAD

**Issue by MorganLug** [MorganLug/Express-REST-TS-API-Template#1]
**Describe the bug**
[Path mapping](https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping) fails to work when running commands `npm start` or `npm windows-dev` (defined in [package.json](https://github.com/MorganLug/Express-REST-TS-API-Template/blob/main/package.json)).
In the case of `npm windows-dev`, it compiles successfully, but you get `var app_1 = __importDefault(require("@App/app"));` in the compiled js for instance.

Path mapping has been defined [here](https://github.com/MorganLug/Express-REST-TS-API-Template/blob/main/tsconfig.json).

**To Reproduce**
1. run `npm start`  

or alternatively :
1. run `npm windows-dev`  

**Error message**
```
npm run windows-dev
...
[nodemon] starting `ts-node ./src/index.ts`
Error: Cannot find module '@App/app'
Require stack:
- C:\Users\Morgan\Documents\Express-REST-TS-API-Template\src\index.ts
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (C:\Users\Morgan\Documents\Express-REST-TS-API-Template\node_modules\@cspotcode\source-map-support\source-map-support.js:679:30)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (C:\Users\Morgan\Documents\Express-REST-TS-API-Template\src\index.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module.m._compile (C:\Users\Morgan\Documents\Express-REST-TS-API-Template\node_modules\ts-node\src\index.ts:1371:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\Morgan\Documents\Express-REST-TS-API-Template\node_modules\ts-node\src\index.ts:1374:12)ules\ts-node\src\index.ts:1374:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Morgan\\Documents\\Express-REST-TS-API-Template\\src\\index.ts'
  ]
}
[nodemon] app crashed - waiting for file changes before starting...

```

**Expected behavior**
The imports must resolve successfully and allow the API to be launched

**Comment by MorganLug** [comment]
Appears `tsconfig` only inform TS of existing mappings, so the compiler doesn't remap the import paths.
I modified the way imports are made to only use `baseUrl` property and set a `NODE_PATH` variable when running commands (see [this commit](https://github.com/MorganLug/Express-REST-TS-API-Template/commit/43df8b74ca81ad1ae8f191372b1a944aac324dc3))
